
name: build

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: lrobin2023

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build apiserver and push
        uses: docker/build-push-action@v3
        with:
          context: apiserver
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/apiserver:${{ steps.vars.outputs.sha_short }}
      - name: Update apiserver chart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'chart/values.yaml'
          commitChange: true
          branch: main
          message: 'Update Image Version to ${{ steps.vars.outputs.sha_short }}'
          title: 'Version Updates'
          changes: |
            {
              "chart/charts/apiserver/values.yaml": {
                "image.tag": "${{ steps.vars.outputs.sha_short }}",
              }
            }